a = (int(input("Ente the value : ")))
b = (int(input("Enter the value 2 : ")))
print("The sum of two numbers : ", a+b)
print("The sub of two numbers : ",a-b)
print("The mul of two numbers : ",a*b)
print("The div of two numbers :",a/b)